//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int IdBook { get; set; }
        public int IdCategory { get; set; }
        public string NameBook { get; set; }
        public string DescriptionBook { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
